version: '2'
services:
    factorio-manager:
        container_name: factorio-manager
        image: "factorio-server-manager"
        restart: always
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/etc/timezone:/etc/timezone:ro"
            - "/factorio/security:/security"
            - "/factorio/saves:/opt/factorio/saves"
            - "/factorio/mods:/opt/factorio/mods"
            - "/factorio/config:/opt/factorio/config"
        ports:
            - "80:80"
            - "443:443"
            - "34197:34197/udp"
